# configuration of picoDAQ buffer manager 

NBuffers: 16                   # number of buffers to store raw waveforms

BMmodules: [mpBufInfo, mpOsci] # buffer manager modules to start

LogFile: BMsum                 # no logging to file if commented out
