# example of a configuration file for PicoScope 2000 Series
PSmodel: 2000a

# channel configuration
#picoChannels: [A, B]
#ChanRanges:   [0.03, 0.35]
picoChannels: [A, B, C, D]
ChanModes:    [AC, AC, AC, AC]
ChanRanges:   [0.03, 0.03, 0.03, 0.03]
sampleTime:   1.0E-04
Nsamples:     500

# trigger
trgActive: true  # true to activate
trgChan:   A
trgThr:    0.015
pretrig:   0.01
trgTyp:    Rising
trgTO:     1000  # time-out

# signal generator
frqSG: 1.0E+02 # 0. to disable, 1.0E-02 lowest
